# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'minesweeper.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bt1 = QtWidgets.QPushButton(self.centralwidget)
        self.bt1.setGeometry(QtCore.QRect(80, 110, 21, 21))
        self.bt1.setText("")
        self.bt1.setObjectName("bt1")
        self.bt2 = QtWidgets.QPushButton(self.centralwidget)
        self.bt2.setGeometry(QtCore.QRect(100, 110, 21, 21))
        self.bt2.setText("")
        self.bt2.setObjectName("bt2")
        self.bt4 = QtWidgets.QPushButton(self.centralwidget)
        self.bt4.setGeometry(QtCore.QRect(140, 110, 21, 21))
        self.bt4.setText("")
        self.bt4.setObjectName("bt4")
        self.bt3 = QtWidgets.QPushButton(self.centralwidget)
        self.bt3.setGeometry(QtCore.QRect(120, 110, 21, 21))
        self.bt3.setText("")
        self.bt3.setObjectName("bt3")
        self.bt8 = QtWidgets.QPushButton(self.centralwidget)
        self.bt8.setGeometry(QtCore.QRect(220, 110, 21, 21))
        self.bt8.setText("")
        self.bt8.setObjectName("bt8")
        self.bt5 = QtWidgets.QPushButton(self.centralwidget)
        self.bt5.setGeometry(QtCore.QRect(160, 110, 21, 21))
        self.bt5.setText("")
        self.bt5.setObjectName("bt5")
        self.bt6 = QtWidgets.QPushButton(self.centralwidget)
        self.bt6.setGeometry(QtCore.QRect(180, 110, 21, 21))
        self.bt6.setText("")
        self.bt6.setObjectName("bt6")
        self.bt7 = QtWidgets.QPushButton(self.centralwidget)
        self.bt7.setGeometry(QtCore.QRect(200, 110, 21, 21))
        self.bt7.setText("")
        self.bt7.setObjectName("bt7")
        self.bt9 = QtWidgets.QPushButton(self.centralwidget)
        self.bt9.setGeometry(QtCore.QRect(240, 110, 21, 21))
        self.bt9.setText("")
        self.bt9.setObjectName("bt9")
        self.bt9_2 = QtWidgets.QPushButton(self.centralwidget)
        self.bt9_2.setGeometry(QtCore.QRect(240, 130, 21, 21))
        self.bt9_2.setText("")
        self.bt9_2.setObjectName("bt9_2")
        self.bt1_2 = QtWidgets.QPushButton(self.centralwidget)
        self.bt1_2.setGeometry(QtCore.QRect(80, 130, 21, 21))
        self.bt1_2.setText("")
        self.bt1_2.setObjectName("bt1_2")
        self.bt4_2 = QtWidgets.QPushButton(self.centralwidget)
        self.bt4_2.setGeometry(QtCore.QRect(140, 130, 21, 21))
        self.bt4_2.setText("")
        self.bt4_2.setObjectName("bt4_2")
        self.bt2_2 = QtWidgets.QPushButton(self.centralwidget)
        self.bt2_2.setGeometry(QtCore.QRect(100, 130, 21, 21))
        self.bt2_2.setText("")
        self.bt2_2.setObjectName("bt2_2")
        self.bt6_2 = QtWidgets.QPushButton(self.centralwidget)
        self.bt6_2.setGeometry(QtCore.QRect(180, 130, 21, 21))
        self.bt6_2.setText("")
        self.bt6_2.setObjectName("bt6_2")
        self.bt5_2 = QtWidgets.QPushButton(self.centralwidget)
        self.bt5_2.setGeometry(QtCore.QRect(160, 130, 21, 21))
        self.bt5_2.setText("")
        self.bt5_2.setObjectName("bt5_2")
        self.bt7_2 = QtWidgets.QPushButton(self.centralwidget)
        self.bt7_2.setGeometry(QtCore.QRect(200, 130, 21, 21))
        self.bt7_2.setText("")
        self.bt7_2.setObjectName("bt7_2")
        self.bt8_2 = QtWidgets.QPushButton(self.centralwidget)
        self.bt8_2.setGeometry(QtCore.QRect(220, 130, 21, 21))
        self.bt8_2.setText("")
        self.bt8_2.setObjectName("bt8_2")
        self.bt3_2 = QtWidgets.QPushButton(self.centralwidget)
        self.bt3_2.setGeometry(QtCore.QRect(120, 130, 21, 21))
        self.bt3_2.setText("")
        self.bt3_2.setObjectName("bt3_2")
        self.bt9_3 = QtWidgets.QPushButton(self.centralwidget)
        self.bt9_3.setGeometry(QtCore.QRect(240, 150, 21, 21))
        self.bt9_3.setText("")
        self.bt9_3.setObjectName("bt9_3")
        self.bt1_3 = QtWidgets.QPushButton(self.centralwidget)
        self.bt1_3.setGeometry(QtCore.QRect(80, 150, 21, 21))
        self.bt1_3.setText("")
        self.bt1_3.setObjectName("bt1_3")
        self.bt4_3 = QtWidgets.QPushButton(self.centralwidget)
        self.bt4_3.setGeometry(QtCore.QRect(140, 150, 21, 21))
        self.bt4_3.setText("")
        self.bt4_3.setObjectName("bt4_3")
        self.bt2_3 = QtWidgets.QPushButton(self.centralwidget)
        self.bt2_3.setGeometry(QtCore.QRect(100, 150, 21, 21))
        self.bt2_3.setText("")
        self.bt2_3.setObjectName("bt2_3")
        self.bt6_3 = QtWidgets.QPushButton(self.centralwidget)
        self.bt6_3.setGeometry(QtCore.QRect(180, 150, 21, 21))
        self.bt6_3.setText("")
        self.bt6_3.setObjectName("bt6_3")
        self.bt5_3 = QtWidgets.QPushButton(self.centralwidget)
        self.bt5_3.setGeometry(QtCore.QRect(160, 150, 21, 21))
        self.bt5_3.setText("")
        self.bt5_3.setObjectName("bt5_3")
        self.bt7_3 = QtWidgets.QPushButton(self.centralwidget)
        self.bt7_3.setGeometry(QtCore.QRect(200, 150, 21, 21))
        self.bt7_3.setText("")
        self.bt7_3.setObjectName("bt7_3")
        self.bt8_3 = QtWidgets.QPushButton(self.centralwidget)
        self.bt8_3.setGeometry(QtCore.QRect(220, 150, 21, 21))
        self.bt8_3.setText("")
        self.bt8_3.setObjectName("bt8_3")
        self.bt3_3 = QtWidgets.QPushButton(self.centralwidget)
        self.bt3_3.setGeometry(QtCore.QRect(120, 150, 21, 21))
        self.bt3_3.setText("")
        self.bt3_3.setObjectName("bt3_3")
        self.bt9_4 = QtWidgets.QPushButton(self.centralwidget)
        self.bt9_4.setGeometry(QtCore.QRect(240, 170, 21, 21))
        self.bt9_4.setText("")
        self.bt9_4.setObjectName("bt9_4")
        self.bt1_4 = QtWidgets.QPushButton(self.centralwidget)
        self.bt1_4.setGeometry(QtCore.QRect(80, 170, 21, 21))
        self.bt1_4.setText("")
        self.bt1_4.setObjectName("bt1_4")
        self.bt4_4 = QtWidgets.QPushButton(self.centralwidget)
        self.bt4_4.setGeometry(QtCore.QRect(140, 170, 21, 21))
        self.bt4_4.setText("")
        self.bt4_4.setObjectName("bt4_4")
        self.bt2_4 = QtWidgets.QPushButton(self.centralwidget)
        self.bt2_4.setGeometry(QtCore.QRect(100, 170, 21, 21))
        self.bt2_4.setText("")
        self.bt2_4.setObjectName("bt2_4")
        self.bt6_4 = QtWidgets.QPushButton(self.centralwidget)
        self.bt6_4.setGeometry(QtCore.QRect(180, 170, 21, 21))
        self.bt6_4.setText("")
        self.bt6_4.setObjectName("bt6_4")
        self.bt5_4 = QtWidgets.QPushButton(self.centralwidget)
        self.bt5_4.setGeometry(QtCore.QRect(160, 170, 21, 21))
        self.bt5_4.setText("")
        self.bt5_4.setObjectName("bt5_4")
        self.bt7_4 = QtWidgets.QPushButton(self.centralwidget)
        self.bt7_4.setGeometry(QtCore.QRect(200, 170, 21, 21))
        self.bt7_4.setText("")
        self.bt7_4.setObjectName("bt7_4")
        self.bt8_4 = QtWidgets.QPushButton(self.centralwidget)
        self.bt8_4.setGeometry(QtCore.QRect(220, 170, 21, 21))
        self.bt8_4.setText("")
        self.bt8_4.setObjectName("bt8_4")
        self.bt3_4 = QtWidgets.QPushButton(self.centralwidget)
        self.bt3_4.setGeometry(QtCore.QRect(120, 170, 21, 21))
        self.bt3_4.setText("")
        self.bt3_4.setObjectName("bt3_4")
        self.bt9_5 = QtWidgets.QPushButton(self.centralwidget)
        self.bt9_5.setGeometry(QtCore.QRect(240, 190, 21, 21))
        self.bt9_5.setText("")
        self.bt9_5.setObjectName("bt9_5")
        self.bt1_5 = QtWidgets.QPushButton(self.centralwidget)
        self.bt1_5.setGeometry(QtCore.QRect(80, 190, 21, 21))
        self.bt1_5.setText("")
        self.bt1_5.setObjectName("bt1_5")
        self.bt4_5 = QtWidgets.QPushButton(self.centralwidget)
        self.bt4_5.setGeometry(QtCore.QRect(140, 190, 21, 21))
        self.bt4_5.setText("")
        self.bt4_5.setObjectName("bt4_5")
        self.bt2_5 = QtWidgets.QPushButton(self.centralwidget)
        self.bt2_5.setGeometry(QtCore.QRect(100, 190, 21, 21))
        self.bt2_5.setText("")
        self.bt2_5.setObjectName("bt2_5")
        self.bt6_5 = QtWidgets.QPushButton(self.centralwidget)
        self.bt6_5.setGeometry(QtCore.QRect(180, 190, 21, 21))
        self.bt6_5.setText("")
        self.bt6_5.setObjectName("bt6_5")
        self.bt5_5 = QtWidgets.QPushButton(self.centralwidget)
        self.bt5_5.setGeometry(QtCore.QRect(160, 190, 21, 21))
        self.bt5_5.setText("")
        self.bt5_5.setObjectName("bt5_5")
        self.bt7_5 = QtWidgets.QPushButton(self.centralwidget)
        self.bt7_5.setGeometry(QtCore.QRect(200, 190, 21, 21))
        self.bt7_5.setText("")
        self.bt7_5.setObjectName("bt7_5")
        self.bt8_5 = QtWidgets.QPushButton(self.centralwidget)
        self.bt8_5.setGeometry(QtCore.QRect(220, 190, 21, 21))
        self.bt8_5.setText("")
        self.bt8_5.setObjectName("bt8_5")
        self.bt3_5 = QtWidgets.QPushButton(self.centralwidget)
        self.bt3_5.setGeometry(QtCore.QRect(120, 190, 21, 21))
        self.bt3_5.setText("")
        self.bt3_5.setObjectName("bt3_5")
        self.bt9_6 = QtWidgets.QPushButton(self.centralwidget)
        self.bt9_6.setGeometry(QtCore.QRect(240, 210, 21, 21))
        self.bt9_6.setText("")
        self.bt9_6.setObjectName("bt9_6")
        self.bt1_6 = QtWidgets.QPushButton(self.centralwidget)
        self.bt1_6.setGeometry(QtCore.QRect(80, 210, 21, 21))
        self.bt1_6.setText("")
        self.bt1_6.setObjectName("bt1_6")
        self.bt4_6 = QtWidgets.QPushButton(self.centralwidget)
        self.bt4_6.setGeometry(QtCore.QRect(140, 210, 21, 21))
        self.bt4_6.setText("")
        self.bt4_6.setObjectName("bt4_6")
        self.bt2_6 = QtWidgets.QPushButton(self.centralwidget)
        self.bt2_6.setGeometry(QtCore.QRect(100, 210, 21, 21))
        self.bt2_6.setText("")
        self.bt2_6.setObjectName("bt2_6")
        self.bt6_6 = QtWidgets.QPushButton(self.centralwidget)
        self.bt6_6.setGeometry(QtCore.QRect(180, 210, 21, 21))
        self.bt6_6.setText("")
        self.bt6_6.setObjectName("bt6_6")
        self.bt5_6 = QtWidgets.QPushButton(self.centralwidget)
        self.bt5_6.setGeometry(QtCore.QRect(160, 210, 21, 21))
        self.bt5_6.setText("")
        self.bt5_6.setObjectName("bt5_6")
        self.bt7_6 = QtWidgets.QPushButton(self.centralwidget)
        self.bt7_6.setGeometry(QtCore.QRect(200, 210, 21, 21))
        self.bt7_6.setText("")
        self.bt7_6.setObjectName("bt7_6")
        self.bt8_6 = QtWidgets.QPushButton(self.centralwidget)
        self.bt8_6.setGeometry(QtCore.QRect(220, 210, 21, 21))
        self.bt8_6.setText("")
        self.bt8_6.setObjectName("bt8_6")
        self.bt3_6 = QtWidgets.QPushButton(self.centralwidget)
        self.bt3_6.setGeometry(QtCore.QRect(120, 210, 21, 21))
        self.bt3_6.setText("")
        self.bt3_6.setObjectName("bt3_6")
        self.bt9_7 = QtWidgets.QPushButton(self.centralwidget)
        self.bt9_7.setGeometry(QtCore.QRect(240, 230, 21, 21))
        self.bt9_7.setText("")
        self.bt9_7.setObjectName("bt9_7")
        self.bt1_7 = QtWidgets.QPushButton(self.centralwidget)
        self.bt1_7.setGeometry(QtCore.QRect(80, 230, 21, 21))
        self.bt1_7.setText("")
        self.bt1_7.setObjectName("bt1_7")
        self.bt4_7 = QtWidgets.QPushButton(self.centralwidget)
        self.bt4_7.setGeometry(QtCore.QRect(140, 230, 21, 21))
        self.bt4_7.setText("")
        self.bt4_7.setObjectName("bt4_7")
        self.bt2_7 = QtWidgets.QPushButton(self.centralwidget)
        self.bt2_7.setGeometry(QtCore.QRect(100, 230, 21, 21))
        self.bt2_7.setText("")
        self.bt2_7.setObjectName("bt2_7")
        self.bt6_7 = QtWidgets.QPushButton(self.centralwidget)
        self.bt6_7.setGeometry(QtCore.QRect(180, 230, 21, 21))
        self.bt6_7.setText("")
        self.bt6_7.setObjectName("bt6_7")
        self.bt5_7 = QtWidgets.QPushButton(self.centralwidget)
        self.bt5_7.setGeometry(QtCore.QRect(160, 230, 21, 21))
        self.bt5_7.setText("")
        self.bt5_7.setObjectName("bt5_7")
        self.bt7_7 = QtWidgets.QPushButton(self.centralwidget)
        self.bt7_7.setGeometry(QtCore.QRect(200, 230, 21, 21))
        self.bt7_7.setText("")
        self.bt7_7.setObjectName("bt7_7")
        self.bt8_7 = QtWidgets.QPushButton(self.centralwidget)
        self.bt8_7.setGeometry(QtCore.QRect(220, 230, 21, 21))
        self.bt8_7.setText("")
        self.bt8_7.setObjectName("bt8_7")
        self.bt3_7 = QtWidgets.QPushButton(self.centralwidget)
        self.bt3_7.setGeometry(QtCore.QRect(120, 230, 21, 21))
        self.bt3_7.setText("")
        self.bt3_7.setObjectName("bt3_7")
        self.bt9_8 = QtWidgets.QPushButton(self.centralwidget)
        self.bt9_8.setGeometry(QtCore.QRect(240, 250, 21, 21))
        self.bt9_8.setText("")
        self.bt9_8.setObjectName("bt9_8")
        self.bt1_8 = QtWidgets.QPushButton(self.centralwidget)
        self.bt1_8.setGeometry(QtCore.QRect(80, 250, 21, 21))
        self.bt1_8.setText("")
        self.bt1_8.setObjectName("bt1_8")
        self.bt4_8 = QtWidgets.QPushButton(self.centralwidget)
        self.bt4_8.setGeometry(QtCore.QRect(140, 250, 21, 21))
        self.bt4_8.setText("")
        self.bt4_8.setObjectName("bt4_8")
        self.bt2_8 = QtWidgets.QPushButton(self.centralwidget)
        self.bt2_8.setGeometry(QtCore.QRect(100, 250, 21, 21))
        self.bt2_8.setText("")
        self.bt2_8.setObjectName("bt2_8")
        self.bt6_8 = QtWidgets.QPushButton(self.centralwidget)
        self.bt6_8.setGeometry(QtCore.QRect(180, 250, 21, 21))
        self.bt6_8.setText("")
        self.bt6_8.setObjectName("bt6_8")
        self.bt5_8 = QtWidgets.QPushButton(self.centralwidget)
        self.bt5_8.setGeometry(QtCore.QRect(160, 250, 21, 21))
        self.bt5_8.setText("")
        self.bt5_8.setObjectName("bt5_8")
        self.bt7_8 = QtWidgets.QPushButton(self.centralwidget)
        self.bt7_8.setGeometry(QtCore.QRect(200, 250, 21, 21))
        self.bt7_8.setText("")
        self.bt7_8.setObjectName("bt7_8")
        self.bt8_8 = QtWidgets.QPushButton(self.centralwidget)
        self.bt8_8.setGeometry(QtCore.QRect(220, 250, 21, 21))
        self.bt8_8.setText("")
        self.bt8_8.setObjectName("bt8_8")
        self.bt3_8 = QtWidgets.QPushButton(self.centralwidget)
        self.bt3_8.setGeometry(QtCore.QRect(120, 250, 21, 21))
        self.bt3_8.setText("")
        self.bt3_8.setObjectName("bt3_8")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(140, 280, 61, 23))
        self.start.setObjectName("start")
        self.score_label = QtWidgets.QLabel(self.centralwidget)
        self.score_label.setGeometry(QtCore.QRect(80, 90, 41, 16))
        self.score_label.setObjectName("score_label")
        self.score = QtWidgets.QLabel(self.centralwidget)
        self.score.setGeometry(QtCore.QRect(120, 90, 141, 16))
        self.score.setText("")
        self.score.setObjectName("score")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.start.setText(_translate("MainWindow", "Start"))
        self.score_label.setText(_translate("MainWindow", "Score:"))

